# Generated by Django 3.1.4 on 2021-01-12 14:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils.search_engine


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageThread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('data', models.TextField(default='{}')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='image_thread', to=settings.AUTH_USER_MODEL)),
            ],
            bases=(models.Model, utils.search_engine.ISearchable),
        ),
        migrations.CreateModel(
            name='ReactionImageThread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('positive_reaction', models.BooleanField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_image', to=settings.AUTH_USER_MODEL)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_image', to='data.imagethread')),
            ],
        ),
        migrations.CreateModel(
            name='DefaultS3Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('order', models.IntegerField()),
                ('content_type', models.CharField(default='image/jpeg', max_length=60)),
                ('bucket', models.CharField(max_length=255)),
                ('object_name', models.CharField(max_length=255)),
                ('thread', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.imagethread')),
            ],
            options={
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='reactionimagethread',
            index=models.Index(fields=['owner', 'thread'], name='data_reacti_owner_i_8f4654_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='reactionimagethread',
            unique_together={('owner', 'thread')},
        ),
        migrations.AddIndex(
            model_name='defaults3image',
            index=models.Index(fields=['thread'], name='data_defaul_thread__cd6af5_idx'),
        ),
    ]
