# Generated by Django 3.1.4 on 2021-01-17 08:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils.search_engine


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('data', models.TextField(default='{}')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            bases=(models.Model, utils.search_engine.ISearchable),
        ),
        migrations.CreateModel(
            name='Novel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bucket', models.CharField(default='resman', max_length=255)),
                ('object_name', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('data', models.TextField(default='{}')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, utils.search_engine.ISearchable),
        ),
        migrations.CreateModel(
            name='VideoList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('data', models.TextField(default='{}')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            bases=(models.Model, utils.search_engine.ISearchable),
        ),
        migrations.CreateModel(
            name='S3Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bucket', models.CharField(default='resman', max_length=255)),
                ('object_name', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('order', models.IntegerField(default=0)),
                ('thread', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.videolist')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='S3Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('order', models.IntegerField()),
                ('content_type', models.CharField(default='image/jpeg', max_length=60)),
                ('bucket', models.CharField(max_length=255)),
                ('object_name', models.CharField(max_length=255)),
                ('thread', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.imagelist')),
            ],
            options={
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReactionToVideoList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('positive_reaction', models.BooleanField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.videolist')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReactionToNovel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('positive_reaction', models.BooleanField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.novel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReactionToImageList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('positive_reaction', models.BooleanField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.imagelist')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='s3video',
            index=models.Index(fields=['thread'], name='data_s3vide_thread__21ade5_idx'),
        ),
        migrations.AddIndex(
            model_name='s3image',
            index=models.Index(fields=['thread'], name='data_s3imag_thread__ac2cf6_idx'),
        ),
        migrations.AddIndex(
            model_name='reactiontovideolist',
            index=models.Index(fields=['owner', 'thread'], name='data_reacti_owner_i_bc7ca4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='reactiontovideolist',
            unique_together={('owner', 'thread')},
        ),
        migrations.AddIndex(
            model_name='reactiontonovel',
            index=models.Index(fields=['owner', 'thread'], name='data_reacti_owner_i_6df9f8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='reactiontonovel',
            unique_together={('owner', 'thread')},
        ),
        migrations.AddIndex(
            model_name='reactiontoimagelist',
            index=models.Index(fields=['owner', 'thread'], name='data_reacti_owner_i_94b449_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='reactiontoimagelist',
            unique_together={('owner', 'thread')},
        ),
    ]
