# Generated by Django 3.2.19 on 2023-05-05 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20210724_1318'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('text', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(fields=('text',), name='unique_tag_text'),
        ),
        migrations.AddField(
            model_name='imagelist',
            name='tags',
            field=models.ManyToManyField(to='data.Tag'),
        ),
        migrations.AddField(
            model_name='novel',
            name='tags',
            field=models.ManyToManyField(to='data.Tag'),
        ),
        migrations.AddField(
            model_name='videolist',
            name='tags',
            field=models.ManyToManyField(to='data.Tag'),
        ),
    ]
