name: Docker Image CI

on:
  push:
    branches:
      - master

jobs:
  path-context:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build image and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64
          push: true
          tags: tsingjyujing/resman:latest
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USER }}/resman:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USER }}/resman:buildcache,mode=max